### ISSUE TITLE
Internal views and dashboards not updating since 2024-11-24

### ISSUE THREAD

**Issue by DimedS** [ClickHouse/clickpy#106]
It seems that the internal views stopped updating on 2024-11-24, which is also the last date displayed on the dashboards:
[clickpy.clickhouse.com](https://clickpy.clickhouse.com/)

<img width="1087" alt="Screenshot 2024-12-02 at 10 44 30" src="https://github.com/user-attachments/assets/3adf5515-e32c-4930-a702-ae3c4ec499b4">

**Comment by gingerwizard** [comment]
Will be updated today. We are moving infrastructure and had some issues.

**Comment by DimedS** [comment]
Thanks, @gingerwizard !

**Comment by gingerwizard** [comment]
Fixed
